//! C++ source emission.
//!
//! Output convention per namespace `ns`:
//! ```text
//! <out>/<ns>/                                  ns may be `::`-nested
//!   <type>_t.hpp                               one header per type
//!   api.hpp                                    publics aggregator (optional)
//!   magic/
//!     <type>_t.start.hpp                       _m000 / _m001 ... expansion shims
//!     <type>_t.end.hpp                         #undef _m000 ... companion
//!     api.start.hpp / api.end.hpp              same pattern for publics
//! ```
//!
//! The `magic/` shim pair is the IN_PARSER toggle: in compile mode it
//! expands to `_SDK_MAGIC_PROPERTY(...)` / `_SDK_MAGIC_BITFIELD(...)` /
//! `_SDK_MAGIC_LINK(...)`; in parser (IntelliSense) mode it elides so the
//! human-readable struct body stays uncluttered. The C++ runtime headers
//! define `IN_PARSER` in parser mode.

use std::fmt::Write;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::emit::EmitOptions;
use crate::ir::{EnumDecl, FieldDecl, FnSig, StructDecl, TypeDecl, TypeRef};
use crate::merge::MergedNamespace;
use crate::name::RustPath;

// Drives emission for one merged namespace into the C++ tree.
pub fn write_unit(ns: &MergedNamespace, out_root: &Path, opts: EmitOptions) -> Result<()> {
    let include_root = out_root.join("include").join("ntbind");
    fs::create_dir_all(&include_root)?;

    // Group anon types under their parent so we can emit them nested inside
    // the parent struct. Top-level types are emitted as standalone `.hpp`
    // files.
    let (top_types, anons_by_parent) = partition_anons(&ns.types);

    for ty in &top_types {
        let (path_rel, body, magic_start, magic_end) =
            render_type(ty, &include_root, &anons_by_parent, opts);
        let ty_path = include_root.join(&path_rel);
        if let Some(parent) = ty_path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&ty_path, body).with_context(|| format!("writing {}", ty_path.display()))?;

        if let (Some(start), Some(end)) = (magic_start, magic_end) {
            let stem = path_rel.file_stem().and_then(|s| s.to_str()).unwrap_or("anon");
            let magic_dir =
                ty_path.parent().expect("type file path always has a parent dir").join("magic");
            fs::create_dir_all(&magic_dir)?;
            fs::write(magic_dir.join(format!("{stem}.start.hpp")), start)?;
            fs::write(magic_dir.join(format!("{stem}.end.hpp")), end)?;
        }
    }

    // Publics deferred to `finalize_tree` so symbols from multiple
    // PDBs that classify into the same target namespace merge into
    // one file instead of clobbering per-PDB.
    Ok(())
}

// No tree-level scaffolding needed for C++ -- every `.hpp` is self-contained
// via `#pragma once`.
pub fn finalize_tree(
    out_root: &Path,
    namespaces: &[MergedNamespace],
    opts: EmitOptions,
) -> Result<()> {
    let include_root = out_root.join("include").join("ntbind");
    fs::create_dir_all(&include_root)?;

    // Bucket publics from every namespace by their classified target
    // namespace; e.g. `KiBugCheckData` from Wdf01000.pdb and
    // `KiProcessorBlock` from ntkrnlmp.pdb both land in `ki/api.hpp`.
    if opts.publics {
        use std::collections::BTreeMap;
        let mut buckets: BTreeMap<String, Vec<(&crate::ir::PublicDecl, &'static str, String)>> =
            BTreeMap::new();
        for ns in namespaces {
            for p in &ns.publics {
                let (target_ns, body) = match crate::name::classify_for_public(&p.rust_name) {
                    Some((ns_, body_)) => (ns_, body_),
                    None => (ns.default_ns.to_owned(), p.rust_name.clone()),
                };
                buckets.entry(target_ns).or_default().push((p, ns.hint_image, body));
            }
        }
        for (target_ns, items) in &buckets {
            write_api_bucket(&include_root, target_ns, items)?;
        }
    }

    // Drop a `.clang-format` with `DisableFormat: true` next to the
    // headers so any clang-format run that follows includes through the
    // tree (IDE save hooks, CI lints) leaves the generated code alone.
    fs::write(
        include_root.join(".clang-format"),
        "# Generated by ntbindgen.  Source is regenerated from PDBs;\n\
         # clang-format has nothing useful to say about the layout.\n\
         DisableFormat: true\n\
         SortIncludes: Never\n",
    )?;
    Ok(())
}

// Split top-level types from anonymous-nested types, keyed by parent's
// PDB-original name (e.g. `_KPROCESS`).
//
fn partition_anons<'a>(
    types: &'a [TypeDecl],
) -> (Vec<&'a TypeDecl>, std::collections::BTreeMap<String, Vec<&'a TypeDecl>>) {
    use std::collections::BTreeMap;
    // First pass: collect top-level type names so we can detect anon's
    // whose computed `parent_of_anon` target isn't actually a top-level
    // type (deep-nested anons under another anon). Those are promoted to
    // top-level emission as sibling files.
    let mut top_orig_names: rustc_hash::FxHashSet<&str> = rustc_hash::FxHashSet::default();
    for ty in types {
        let (orig, ns_name) = match ty {
            TypeDecl::Struct(s) | TypeDecl::Union(s) => {
                (s.original_name.as_str(), s.path.name.as_str())
            },
            TypeDecl::Enum(e) => (e.original_name.as_str(), e.path.name.as_str()),
            TypeDecl::Stub(s) => (s.original_name.as_str(), s.path.name.as_str()),
        };
        if parent_of_anon(ns_name, orig).is_none() {
            top_orig_names.insert(orig);
        }
    }

    let mut top = Vec::new();
    let mut anons: BTreeMap<String, Vec<&'a TypeDecl>> = BTreeMap::new();
    for ty in types {
        let (orig, ns_name) = match ty {
            TypeDecl::Struct(s) | TypeDecl::Union(s) => {
                (s.original_name.as_str(), s.path.name.as_str())
            },
            TypeDecl::Enum(e) => (e.original_name.as_str(), e.path.name.as_str()),
            TypeDecl::Stub(s) => (s.original_name.as_str(), s.path.name.as_str()),
        };
        match parent_of_anon(ns_name, orig) {
            Some(parent_orig) if top_orig_names.contains(parent_orig) => {
                anons.entry(parent_orig.to_owned()).or_default().push(ty);
            },
            // Anon whose parent is another anon (deep nesting) -- promote
            // to top-level emission as a sibling file. The parent's body
            // references it by absolute namespace path.
            _ => top.push(ty),
        }
    }
    (top, anons)
}

// Recover the parent's PDB-original name from a synthetic anon type's
// own name + original. Returns `None` when the type isn't an anon.
//
fn parent_of_anon<'a>(ns_name: &str, original: &'a str) -> Option<&'a str> {
    // Synthetic ns_name pattern: `<parent_stem>_u<N>_<field>_t`.  The
    // parent_stem may itself contain `_u<non-digit>` substrings (PDB
    // names with `_unmask`, `_user`, ...), so keep scanning past any
    // `_u` not followed by a digit until we find `_u<digit>` or run
    // out of input.
    let mut search_from = 0usize;
    while let Some(rel) = ns_name[search_from..].find("_u") {
        let pos = search_from + rel;
        let suffix = &ns_name[pos + 2..];
        if suffix.starts_with(|c: char| c.is_ascii_digit()) {
            // The synthetic original is `<parent_orig>_<synthetic_name>`.
            // We don't have the synthetic_name's exact length here, but
            // `original` ends with `_<ns_name>` -- strip that to recover
            // the parent's PDB original name.
            let trailing = format!("_{ns_name}");
            return original.strip_suffix(&trailing);
        }
        // Advance past this `_u` and keep looking.
        search_from = pos + 2;
    }
    None
}

fn render_type(
    t: &TypeDecl,
    include_root: &Path,
    anons_by_parent: &std::collections::BTreeMap<String, Vec<&TypeDecl>>,
    opts: EmitOptions,
) -> (PathBuf, String, Option<String>, Option<String>) {
    let _ = include_root;
    match t {
        TypeDecl::Struct(s) => {
            let (body, start, end) = render_struct(s, false, anons_by_parent, opts);
            (file_path(&s.path), body, Some(start), Some(end))
        },
        TypeDecl::Union(s) => {
            let (body, start, end) = render_struct(s, true, anons_by_parent, opts);
            (file_path(&s.path), body, Some(start), Some(end))
        },
        TypeDecl::Enum(e) => (file_path(&e.path), render_enum(e), None, None),
        TypeDecl::Stub(s) => (file_path(&s.path), render_stub_cpp(s), None, None),
    }
}

// Minimal `.hpp` for an orphan pointee -- just a forward declaration so
// the type name resolves at the `*` site without needing the full
// `.symtbl`/`SDK_VERIFY` boilerplate.
//
fn render_stub_cpp(s: &crate::ir::StubDecl) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// @generated by ntbindgen.  Do not edit.");
    let _ = writeln!(out, "// clang-format off");
    let _ = writeln!(out, "#pragma once");
    let kw = match s.kind {
        crate::ir::PointeeKind::Struct => "struct",
        crate::ir::PointeeKind::Union => "union",
        crate::ir::PointeeKind::Enum => "enum class",
    };
    let _ = writeln!(out, "namespace {} {{ {kw} {}; }}", s.path.ns, s.path.name);
    out
}

fn file_path(p: &RustPath) -> PathBuf {
    let mut path = PathBuf::new();
    for seg in p.ns.split("::") {
        path.push(seg);
    }
    path.push(format!("{}.hpp", p.name));
    path
}

// Render a struct/union `.hpp` body. Returns (body, magic.start, magic.end).
//
fn render_struct(
    s: &StructDecl,
    is_union: bool,
    anons_by_parent: &std::collections::BTreeMap<String, Vec<&TypeDecl>>,
    opts: EmitOptions,
) -> (String, String, String) {
    let kw = if is_union { "union" } else { "struct" };
    let mut body = String::new();
    let _ = writeln!(body, "// @generated by ntbindgen.  Do not edit.");
    let _ = writeln!(body, "// clang-format off");
    let _ = writeln!(body, "#pragma once");
    let _ = writeln!(body, "#include <ntbind/support_library.hpp>");
    let _ = writeln!(body);

    // Forward declarations for typed pointer pointees.  One
    // `namespace <ns> { <kw> <name>; }` per distinct pointee; saves us
    // from `#include`'ing each pointee header.
    let mut fwds = gather_forward_decls(&s.fields, &s.path);
    let inlined_anons = anons_by_parent.get(&s.original_name);
    if let Some(anons) = inlined_anons {
        for anon in anons {
            if let TypeDecl::Struct(c) | TypeDecl::Union(c) = anon {
                fwds.extend(gather_forward_decls(&c.fields, &s.path));
            }
        }
    }
    fwds.sort_by(|a, b| a.0.ns.cmp(&b.0.ns).then(a.0.name.cmp(&b.0.name)));
    fwds.dedup_by(|a, b| a.0.ns == b.0.ns && a.0.name == b.0.name);
    // Structs/unions get forward decls; enums get a FULL `#include`
    // because an `enum class X;` forward decl without explicit
    // underlying type defaults to `int`, mismatching any later full
    // decl whose underlying type is `uint8_t`/`uint16_t`/`uint64_t`.
    //
    let mut enum_includes: Vec<RustPath> = Vec::new();
    fwds.retain(|(path, kind)| {
        if matches!(kind, crate::ir::PointeeKind::Enum) {
            enum_includes.push(path.clone());
            false
        } else {
            true
        }
    });
    for (path, kind) in &fwds {
        let kw = match kind {
            crate::ir::PointeeKind::Struct => "struct",
            crate::ir::PointeeKind::Union => "union",
            crate::ir::PointeeKind::Enum => unreachable!("enums routed to includes above"),
        };
        // C++17 nested-namespace form keeps single-line forward decls
        // workable for `dxgk::arg::cb` style paths.
        let _ = writeln!(body, "namespace {} {{ {kw} {}; }}", path.ns, path.name);
    }
    if !fwds.is_empty() {
        let _ = writeln!(body);
    }

    // Cross-file `#include` set -- only `UserDefined` (embedded) references
    // need the actual definition; `TypedPointer` is handled above via the
    // forward decls.
    let mut deps: Vec<RustPath> = gather_user_deps(&s.fields, &s.path);
    if let Some(anons) = inlined_anons {
        for anon in anons {
            if let TypeDecl::Struct(c) | TypeDecl::Union(c) = anon {
                deps.extend(gather_user_deps(&c.fields, &s.path));
            }
        }
    }
    let inlined_names: rustc_hash::FxHashSet<(String, String)> = inlined_anons
        .map(|a| {
            a.iter()
                .map(|t| match t {
                    TypeDecl::Struct(c) | TypeDecl::Union(c) => {
                        (c.path.ns.clone(), c.path.name.clone())
                    },
                    TypeDecl::Enum(e) => (e.path.ns.clone(), e.path.name.clone()),
                    TypeDecl::Stub(s) => (s.path.ns.clone(), s.path.name.clone()),
                })
                .collect()
        })
        .unwrap_or_default();
    deps.extend(enum_includes);
    deps.retain(|p| !inlined_names.contains(&(p.ns.clone(), p.name.clone())));
    deps.sort();
    deps.dedup();
    if !deps.is_empty() {
        // Same-namespace deps use a bare include (`"<name>.hpp"`),
        // cross-namespace deps walk up to `<include_root>/ntbind` and back
        // down.  Without the same-ns special case, clang's
        // `-Wmicrosoft-include` flags the redundant `../<ns>/` prefix as
        // non-portable resolution under `-Werror`.
        let depth = s.path.ns.split("::").count();
        let up_prefix: String = "../".repeat(depth);
        for p in &deps {
            if p.ns == s.path.ns {
                let _ = writeln!(body, "#include \"{}.hpp\"", p.name);
            } else {
                let dep_dir: String = p.ns.replace("::", "/");
                let _ = writeln!(body, "#include \"{up_prefix}{dep_dir}/{}.hpp\"", p.name);
            }
        }
        let _ = writeln!(body);
    }
    let _ = writeln!(body, "#include \"magic/{}.start.hpp\"", s.path.name);
    let ns_open = ns_open(&s.path.ns);
    let _ = write!(body, "{ns_open}");
    let _ = writeln!(body, "    // [{kw} {}]", s.original_name);
    let _ = writeln!(body, "    // => Windows 10 v20H2");
    let _ = writeln!(body, "    //");
    let _ = writeln!(body, "    {kw} {}", s.path.name);
    let _ = writeln!(body, "    {{");

    // Inline anon nested types from this parent.  We thread the
    // running field-index offset so each anon's `_mNNN` references
    // line up with the macro definitions emitted by
    // `render_magic_shim`, which numbers anons first then the outer
    // body in a single continuous counter.
    let mut anon_field_offset = 0usize;
    if let Some(anons) = anons_by_parent.get(&s.original_name) {
        for anon in anons {
            let dotted_prefix = anon_wire_prefix(&s.original_name, &s.fields, anon);
            let inner_len = match anon {
                TypeDecl::Struct(c) | TypeDecl::Union(c) => c.fields.len(),
                _ => 0,
            };
            match anon {
                TypeDecl::Struct(child) => emit_inline_struct(
                    &mut body,
                    child,
                    false,
                    &dotted_prefix,
                    opts,
                    anon_field_offset,
                ),
                TypeDecl::Union(child) => emit_inline_struct(
                    &mut body,
                    child,
                    true,
                    &dotted_prefix,
                    opts,
                    anon_field_offset,
                ),
                TypeDecl::Enum(child) => emit_inline_enum(&mut body, child),
                // Anon-nested stubs don't occur -- Stubs are top-level.
                TypeDecl::Stub(_) => {},
            }
            anon_field_offset += inner_len;
            let _ = writeln!(body);
        }
    }

    let _ = writeln!(body, "        // Windows 10 v20H2");
    let _ = writeln!(body, "        //");

    // Field accessors: `_mNNN <type> <name>;  //{ +0x<off>[@<bit>] } | .<Orig>`.
    // Names of inlined anons (with their full ns) so we render their bare
    // name when a parent field references them -- they're in-scope here.
    let inlined_paths: rustc_hash::FxHashSet<(String, String)> = inlined_anons
        .map(|a| {
            a.iter()
                .map(|t| match t {
                    TypeDecl::Struct(s) | TypeDecl::Union(s) => {
                        (s.path.ns.clone(), s.path.name.clone())
                    },
                    TypeDecl::Enum(e) => (e.path.ns.clone(), e.path.name.clone()),
                    TypeDecl::Stub(s) => (s.path.ns.clone(), s.path.name.clone()),
                })
                .collect()
        })
        .unwrap_or_default();

    let aliases = collect_long_aliases(&s.fields, &inlined_paths);
    if !aliases.decls.is_empty() {
        for (alias_name, ty) in &aliases.decls {
            let _ = writeln!(body, "        using {alias_name} = {ty};");
        }
        let _ = writeln!(body);
    }

    let widths = compute_field_widths(&s.fields, &inlined_paths, &aliases);
    for (i, f) in s.fields.iter().enumerate() {
        emit_visible_field_indented(
            &mut body,
            anon_field_offset + i,
            f,
            &widths,
            "        ",
            &inlined_paths,
            aliases.by_field.get(&i).map(|s| s.as_str()),
        );
    }

    let _ = writeln!(body);
    let _ = writeln!(
        body,
        "        SDK_MAGIC_PROPERTIES( \"{}.$\", 0x{:x}, true, 0x{:x} );",
        s.original_name,
        s.size.max(1),
        s.summary_key,
    );
    let _ = writeln!(body, "        SDK_FIXED_SIZE( {}, 0x{:x} );", s.path.name, s.size.max(1),);
    let _ = writeln!(body, "    }};");
    let _ = write!(body, "{}", ns_close(&s.path.ns));
    let _ = writeln!(body, "#include \"magic/{}.end.hpp\"", s.path.name);

    // SDK_VERIFY lines -- one per anon (in the nested form `parent::child_t`)
    // plus one for the top-level type.
    if let Some(anons) = anons_by_parent.get(&s.original_name) {
        for anon in anons {
            let (kind, child_path, child_name, child_size) = match anon {
                TypeDecl::Struct(c) => ("struct", &c.path.ns, &c.path.name, c.size),
                TypeDecl::Union(c) => ("union", &c.path.ns, &c.path.name, c.size),
                TypeDecl::Enum(c) => ("enum", &c.path.ns, &c.path.name, 4),
                TypeDecl::Stub(_) => continue,
            };
            let _ = writeln!(
                body,
                "SDK_VERIFY( {kind} {path}::{outer}::{child}, 0x{size:x} );",
                path = ns_to_cpp(child_path),
                outer = s.path.name,
                child = child_name,
                size = child_size.max(1)
            );
        }
    }
    let _ = writeln!(
        body,
        "SDK_VERIFY( {kw} {path}::{}, 0x{:x} );",
        s.path.name,
        s.size.max(1),
        path = ns_to_cpp(&s.path.ns),
    );

    // magic/<name>.start.hpp and .end.hpp shim bodies.
    let (magic_start, magic_end) =
        render_magic_shim(&s.original_name, &s.fields, s, anons_by_parent);
    (body, magic_start, magic_end)
}

// Emit a nested anon type INSIDE the parent struct body.
// Includes its own SDK_MAGIC_PROPERTIES + SDK_FIXED_SIZE.
//
fn emit_inline_struct(
    out: &mut String,
    c: &StructDecl,
    is_union: bool,
    wire_ident_base: &str,
    opts: EmitOptions,
    field_index_offset: usize,
) {
    let kw = if is_union { "union" } else { "struct" };
    let _ = writeln!(out, "        {kw} {}", c.path.name);
    let _ = writeln!(out, "        {{");
    let _ = writeln!(out, "            // Windows 10 v20H2");
    let _ = writeln!(out, "            //");

    let aliases = collect_long_aliases(&c.fields, &Default::default());
    if !aliases.decls.is_empty() {
        for (alias_name, ty) in &aliases.decls {
            let _ = writeln!(out, "            using {alias_name} = {ty};");
        }
        let _ = writeln!(out);
    }

    let widths = compute_field_widths(&c.fields, &Default::default(), &aliases);
    for (i, f) in c.fields.iter().enumerate() {
        emit_visible_field_indented(
            out,
            field_index_offset + i,
            f,
            &widths,
            "            ",
            &Default::default(),
            aliases.by_field.get(&i).map(|s| s.as_str()),
        );
    }

    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "            SDK_MAGIC_PROPERTIES( \"{}.$\", 0x{:x}, true, 0x{:x} );",
        wire_ident_base,
        c.size.max(1),
        summary_key(wire_ident_base, opts),
    );
    let _ = writeln!(out, "            SDK_FIXED_SIZE( {}, 0x{:x} );", c.path.name, c.size.max(1),);
    let _ = writeln!(out, "        }};");
}

// Recover the canonical wire identifier prefix for an anonymous nested
// type -- `<ParentOrig>.<FieldNameCamelCase>`. The IR doesn't store the
// field-name -> anon-type association directly; we walk the parent's
// field list looking for a `UserDefined` reference matching the anon's
// path.
// Walk a field list and collect cross-file dependencies as relative
// include paths anchored to the current file. The returned strings are
// the prefix without `.hpp` (e.g. `nt/foo_t`, `bar_t`).
//
// `current` is the path of the file we're emitting -- used to skip
// self-references and to compute the relative path: we emit
// `"../<rel>.hpp"` so a header at `<out>/include/ntbind/<ns>/<file>.hpp`
// resolves includes against `<out>/include/ntbind/`.
//
fn gather_user_deps(fields: &[FieldDecl], current: &RustPath) -> Vec<RustPath> {
    fn walk(t: &TypeRef, out: &mut Vec<RustPath>) {
        match t {
            TypeRef::UserDefined(p) => out.push(p.clone()),
            TypeRef::Array { element, .. } => walk(element, out),
            // Recurse through pointer wrappers so a `UserDefined` lying
            // behind one or more `Ref` / `FnPtr` layers still surfaces.
            TypeRef::Ref(inner) | TypeRef::Volatile(inner) => walk(inner, out),
            TypeRef::FnPtr(sig) => {
                walk(&sig.return_type, out);
                for p in &sig.params {
                    walk(p, out);
                }
            },
            TypeRef::Primitive(_)
            | TypeRef::Pointer
            | TypeRef::TypedPointer { .. }
            | TypeRef::External { .. }
            | TypeRef::Opaque(_) => {},
        }
    }
    let mut paths: Vec<RustPath> = Vec::new();
    for f in fields {
        walk(&f.ty, &mut paths);
    }
    paths.retain(|p| !(p.ns == current.ns && p.name == current.name));
    paths
}

// Walk the same field list collecting *forward-declarable* pointees --
// `TypeRef::TypedPointer` references. The C++ emitter prints these as
// `namespace <ns> { <kw> <name>; }` lines at the top of the header, which
// is enough to type the pointer itself without `#include`'ing the
// pointee's full definition.
//
fn gather_forward_decls(
    fields: &[FieldDecl],
    current: &RustPath,
) -> Vec<(RustPath, crate::ir::PointeeKind)> {
    fn walk(t: &TypeRef, out: &mut Vec<(RustPath, crate::ir::PointeeKind)>) {
        match t {
            TypeRef::TypedPointer { path, kind, .. } => out.push((path.clone(), *kind)),
            TypeRef::Array { element, .. } => walk(element, out),
            // Forward-decl walkers recurse into typed-pointer carriers
            // so a nested `TypedPointer` inside a fn-pointer parameter
            // still gets a forward declaration emitted.
            TypeRef::Ref(inner) | TypeRef::Volatile(inner) => walk(inner, out),
            TypeRef::FnPtr(sig) => {
                walk(&sig.return_type, out);
                for p in &sig.params {
                    walk(p, out);
                }
            },
            TypeRef::Primitive(_)
            | TypeRef::Pointer
            | TypeRef::UserDefined(_)
            | TypeRef::External { .. }
            | TypeRef::Opaque(_) => {},
        }
    }
    let mut out = Vec::new();
    for f in fields {
        walk(&f.ty, &mut out);
    }
    out.retain(|(p, _)| !(p.ns == current.ns && p.name == current.name));
    out.sort_by(|a, b| a.0.ns.cmp(&b.0.ns).then(a.0.name.cmp(&b.0.name)));
    out.dedup_by(|a, b| a.0.ns == b.0.ns && a.0.name == b.0.name);
    out
}

fn anon_wire_prefix(parent_original: &str, parent_fields: &[FieldDecl], anon: &TypeDecl) -> String {
    let anon_path = match anon {
        TypeDecl::Struct(s) | TypeDecl::Union(s) => &s.path,
        TypeDecl::Enum(e) => &e.path,
        TypeDecl::Stub(s) => &s.path,
    };
    for f in parent_fields {
        if let TypeRef::UserDefined(p) = &f.ty
            && p.ns == anon_path.ns
            && p.name == anon_path.name
        {
            return format!("{parent_original}.{}", f.original_name);
        }
    }
    // Fallback: anon wasn't referenced by a struct field -- happens for
    // synthesized-but-orphaned anons. Use the IR's collapsed form.
    match anon {
        TypeDecl::Struct(s) | TypeDecl::Union(s) => s.original_name.clone(),
        TypeDecl::Enum(e) => e.original_name.clone(),
        TypeDecl::Stub(s) => s.original_name.clone(),
    }
}

// Format an enum variant's i128 value as unsigned hex masked to the
// underlying-type width, so a negative `0x80000001` for an i32-underlying
// enum prints as 8 hex digits rather than sign-extended to 32.
fn fmt_enum_value(value: i128, underlying: &TypeRef) -> String {
    let bits: u32 = match underlying {
        TypeRef::Primitive(p) => match *p {
            "i8" | "u8" | "char" => 8,
            "i16" | "u16" | "wchar" => 16,
            "i32" | "u32" => 32,
            "i64" | "u64" => 64,
            "i128" | "u128" => 128,
            _ => 64,
        },
        _ => 64,
    };
    if bits >= 128 {
        return format!("0x{:x}", value as u128);
    }
    let mask: u128 = (1u128 << bits) - 1;
    let masked = (value as u128) & mask;
    format!("0x{:x}", masked)
}

fn emit_inline_enum(out: &mut String, e: &EnumDecl) {
    let underlying = render_cpp_type(&e.underlying);
    let _ = writeln!(out, "        enum class {} : {}", e.path.name, underlying);
    let _ = writeln!(out, "        {{");
    for v in &e.variants {
        let unescaped = cpp_unescape_rust_only_keyword(&v.rust_name);
        let cpp_name = cpp_escape_keyword(unescaped);
        let val_str = fmt_enum_value(v.value, &e.underlying);
        let tag = v.build_tag.unwrap_or("Windows 10 v20H2");
        let _ = writeln!(out, "            {} = {},    // {}", cpp_name, val_str, tag);
    }
    let _ = writeln!(out, "        }};");
}

// Fields whose rendered C++ type exceeds `LONG_TYPE_NAME_LIMIT` chars
// get a `using <field>_t = <type>;` alias at struct scope; the field
// declaration then references the alias for readability and to give
// downstream code a stable scoped name to spell out.
//
const LONG_TYPE_NAME_LIMIT: usize = 48;

#[derive(Default)]
struct FieldAliases {
    // field index -> alias name (for substituting in the field declaration)
    by_field: rustc_hash::FxHashMap<usize, String>,
    // emission order: (alias_name, rendered_type)
    decls: Vec<(String, String)>,
}

fn collect_long_aliases(
    fields: &[FieldDecl],
    inlined: &rustc_hash::FxHashSet<(String, String)>,
) -> FieldAliases {
    let mut out = FieldAliases::default();
    for (i, f) in fields.iter().enumerate() {
        // Bitfields render to `uintN_t` -- never long enough to trigger.
        if f.bitfield.is_some() {
            continue;
        }
        let ty = render_field_type_cpp_scoped(f, inlined);
        if ty.chars().count() > LONG_TYPE_NAME_LIMIT {
            let base = cpp_unescape_rust_only_keyword(&f.rust_name);
            let alias = format!("{}_t", base);
            out.by_field.insert(i, alias.clone());
            out.decls.push((alias, ty));
        }
    }
    out
}

#[derive(Default)]
struct FieldWidths {
    type_col: usize,
    name_col: usize,
}

fn compute_field_widths(
    fields: &[FieldDecl],
    inlined: &rustc_hash::FxHashSet<(String, String)>,
    aliases: &FieldAliases,
) -> FieldWidths {
    let mut w = FieldWidths::default();
    for (i, f) in fields.iter().enumerate() {
        let ty = match aliases.by_field.get(&i) {
            Some(a) => a.clone(),
            None => render_field_type_cpp_scoped(f, inlined),
        };
        w.type_col = w.type_col.max(ty.chars().count());
        let nm_len = f.rust_name.chars().count() + 1; // trailing `;`
        w.name_col = w.name_col.max(nm_len);
    }
    w
}

fn emit_visible_field_indented(
    out: &mut String,
    idx: usize,
    f: &FieldDecl,
    w: &FieldWidths,
    indent: &str,
    inlined: &rustc_hash::FxHashSet<(String, String)>,
    alias: Option<&str>,
) {
    let ty = match alias {
        Some(a) => a.to_owned(),
        None => render_field_type_cpp_scoped(f, inlined),
    };
    let byte_off = f.bit_offset / 8;
    let off_comment = if f.bitfield.is_some() {
        format!("+0x{:04x}@{}", byte_off, f.bit_offset % 8)
    } else {
        format!("+0x{:04x}   ", byte_off)
    };
    // `rust_name` was Rust-escaped during lowering; unescape Rust-only
    // keywords (e.g. `type_` -> `type`) before applying the C++ escape.
    let cpp_base = cpp_unescape_rust_only_keyword(&f.rust_name);
    let cpp_name = cpp_escape_keyword(cpp_base);
    let _ = writeln!(
        out,
        "{indent}_m{idx:03} {ty:<tc$} {nm:<nc$}  //{{ {off:<10} }} | .{orig}",
        idx = idx,
        ty = ty,
        tc = w.type_col,
        nm = format!("{};", cpp_name),
        nc = w.name_col,
        off = off_comment,
        orig = f.original_name,
    );
}

// Reverse a Rust-only keyword escape: trailing `_` on words reserved
// in Rust but not C++ (e.g. `type_` -> `type`).
//
fn cpp_unescape_rust_only_keyword(name: &str) -> &str {
    if let Some(stripped) = name.strip_suffix('_') {
        const RUST_ONLY: &[&str] = &[
            "type", "fn", "mut", "ref", "let", "impl", "match", "use", "trait", "where", "move",
            "crate", "mod", "pub", "self", "Self", "super", "loop", "as", "in", "box", "macro",
            "yield", "async", "await", "dyn",
        ];
        if RUST_ONLY.contains(&stripped) {
            return stripped;
        }
    }
    name
}

// Prefix the C++ keyword set with `_` so a field name like `class` /
// `delete` / `new` produces a valid C++ identifier.
//
fn cpp_escape_keyword(name: &str) -> std::borrow::Cow<'_, str> {
    const KEYWORDS: &[&str] = &[
        "alignas",
        "alignof",
        "and",
        "and_eq",
        "asm",
        "auto",
        "bitand",
        "bitor",
        "bool",
        "break",
        "case",
        "catch",
        "char",
        "char8_t",
        "char16_t",
        "char32_t",
        "class",
        "compl",
        "concept",
        "const",
        "consteval",
        "constexpr",
        "constinit",
        "const_cast",
        "continue",
        "co_await",
        "co_return",
        "co_yield",
        "decltype",
        "default",
        "delete",
        "do",
        "double",
        "dynamic_cast",
        "else",
        "enum",
        "explicit",
        "export",
        "extern",
        "false",
        "float",
        "for",
        "friend",
        "goto",
        "if",
        "inline",
        "int",
        "long",
        "mutable",
        "namespace",
        "new",
        "noexcept",
        "not",
        "not_eq",
        "nullptr",
        "operator",
        "or",
        "or_eq",
        "private",
        "protected",
        "public",
        "register",
        "reinterpret_cast",
        "requires",
        "return",
        "short",
        "signed",
        "sizeof",
        "static",
        "static_assert",
        "static_cast",
        "struct",
        "switch",
        "template",
        "this",
        "thread_local",
        "throw",
        "true",
        "try",
        "typedef",
        "typeid",
        "typename",
        "union",
        "unsigned",
        "using",
        "virtual",
        "void",
        "volatile",
        "wchar_t",
        "while",
        "xor",
        "xor_eq",
    ];
    if KEYWORDS.contains(&name) {
        std::borrow::Cow::Owned(format!("_{name}"))
    } else {
        std::borrow::Cow::Borrowed(name)
    }
}

fn render_magic_shim(
    parent_original: &str,
    fields: &[FieldDecl],
    parent: &StructDecl,
    anons_by_parent: &std::collections::BTreeMap<String, Vec<&TypeDecl>>,
) -> (String, String) {
    let mut start = String::new();
    let mut end = String::new();
    let _ = writeln!(start, "// @generated by ntbindgen.  Do not edit.");
    let _ = writeln!(start, "// clang-format off");
    let _ = writeln!(start, "#if !IN_PARSER");

    // Nested anons contribute their own `_mNNN` shims too -- merge all
    // bodies into the parent's magic file so a single include of the
    // parent's magic.start brings every nested macro into scope.
    //
    // Inlined anon types live in the parent's class scope (not in
    // their declared namespace), so a field whose type names one of
    // them must reference the bare name -- pre-build the set and pass
    // it through to `emit_macro_line`.
    let inlined_paths: rustc_hash::FxHashSet<(String, String)> = anons_by_parent
        .get(parent_original)
        .map(|a| {
            a.iter()
                .map(|t| match t {
                    TypeDecl::Struct(s) | TypeDecl::Union(s) => {
                        (s.path.ns.clone(), s.path.name.clone())
                    },
                    TypeDecl::Enum(e) => (e.path.ns.clone(), e.path.name.clone()),
                    TypeDecl::Stub(s) => (s.path.ns.clone(), s.path.name.clone()),
                })
                .collect()
        })
        .unwrap_or_default();
    let mut counter = 0u32;
    let anons = anons_by_parent.get(parent_original);
    if let Some(anons) = anons {
        for anon in anons {
            let inner_fields: &[FieldDecl] = match anon {
                TypeDecl::Struct(c) | TypeDecl::Union(c) => &c.fields,
                TypeDecl::Enum(_) | TypeDecl::Stub(_) => continue,
            };
            for f in inner_fields {
                emit_macro_line(&mut start, counter, f, &inlined_paths);
                counter += 1;
            }
        }
    }
    for f in fields {
        emit_macro_line(&mut start, counter, f, &inlined_paths);
        counter += 1;
    }

    let _ = writeln!(start, "#else");
    for i in 0..counter {
        let _ = writeln!(start, "#define _m{i:03}");
    }
    let _ = writeln!(start, "#endif");

    for i in 0..counter {
        let _ = writeln!(end, "#undef _m{i:03}");
    }
    let end = format!("// @generated by ntbindgen.  Do not edit.\n// clang-format off\n{end}");
    let _ = parent;
    (start, end)
}

fn emit_macro_line(
    out: &mut String,
    counter: u32,
    f: &FieldDecl,
    inlined: &rustc_hash::FxHashSet<(String, String)>,
) {
    let identifier = &f.identifier;
    let ty = render_field_type_cpp_scoped(f, inlined);
    // The `field` macro arg is pasted into `xstrcat(__entry_, field)`,
    // so it must match the unescaped name used in the struct body --
    // otherwise `SDK_OFFSET(s, type)` resolves to `__entry_type` while
    // the struct declares `__entry_type_`.
    let macro_name = cpp_unescape_rust_only_keyword(&f.rust_name);
    if let Some(bf) = &f.bitfield {
        let storage_type = match bf.storage_bytes {
            1 => "uint8_t",
            2 => "uint16_t",
            4 => "uint32_t",
            8 => "uint64_t",
            _ => "uint32_t",
        };
        let _ = writeln!(
            out,
            "#define _m{c:03} _SDK_MAGIC_BITFIELD(nop_t, _SDK_ESCAPE({ty}), \"{ident}\", {name}, 0x{boff:x}, 0x{bsize:x}, true, 0x{key:x}, {bsize_dec}, {storage})",
            c = counter,
            ty = ty,
            ident = identifier,
            name = macro_name,
            boff = f.bit_offset,
            bsize = f.bit_size,
            bsize_dec = f.bit_size,
            key = f.key,
            storage = storage_type,
        );
    } else {
        let _ = writeln!(
            out,
            "#define _m{c:03} _SDK_MAGIC_PROPERTY(_SDK_ESCAPE({ty}), \"{ident}\", {name}, 0x{boff:x}, 0x{bsize:x}, true, 0x{key:x})",
            c = counter,
            ty = ty,
            ident = identifier,
            name = macro_name,
            boff = f.bit_offset,
            bsize = f.bit_size,
            key = f.key,
        );
    }
}

fn ns_to_cpp(ns: &str) -> String {
    ns.to_owned()
}

fn ns_open(ns: &str) -> String {
    let mut s = String::new();
    for seg in ns.split("::") {
        let _ = writeln!(s, "namespace {seg}");
        let _ = writeln!(s, "{{");
    }
    s
}

fn ns_close(ns: &str) -> String {
    let mut s = String::new();
    for _ in ns.split("::") {
        let _ = writeln!(s, "}};");
    }
    s
}

fn summary_key(parent_original: &str, opts: EmitOptions) -> u64 {
    if opts.no_encrypt { 0 } else { crate::name::sdbm_hash(&format!("{parent_original}.$")) }
}

fn render_enum(e: &EnumDecl) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// @generated by ntbindgen.  Do not edit.");
    let _ = writeln!(out, "// clang-format off");
    let _ = writeln!(out, "#pragma once");
    let _ = writeln!(out, "#include <ntbind/support_library.hpp>");
    let _ = writeln!(out);
    let _ = write!(out, "{}", ns_open(&e.path.ns));
    let _ = writeln!(out, "    // [enum {}]", e.original_name);
    let _ = writeln!(out, "    //  Windows 10 v20H2");
    let _ = writeln!(out, "    //");
    let underlying = render_cpp_type(&e.underlying);
    let _ = writeln!(out, "    enum class {} : {}", e.path.name, underlying);
    let _ = writeln!(out, "    {{");
    // Allow duplicate values directly in `enum class`.  Sort variants by
    // (value, name) ascending.  Alignment widths are computed against the
    // sorted set so the `=` column stays stable.
    let mut sorted: Vec<&_> = e.variants.iter().collect();
    sorted.sort_by(|a, b| a.value.cmp(&b.value).then_with(|| a.rust_name.cmp(&b.rust_name)));
    // Unescape Rust-only keywords (`type_` -> `type`), then escape
    // C++ keywords (`default` -> `_default`); enum variants like
    // `default`, `mutable`, `dynamic` would otherwise fail to compile.
    let cpp_names: Vec<String> = sorted
        .iter()
        .map(|v| {
            let unescaped = cpp_unescape_rust_only_keyword(&v.rust_name);
            cpp_escape_keyword(unescaped).into_owned()
        })
        .collect();
    let max_name = cpp_names.iter().map(|n| n.chars().count()).max().unwrap_or(0);
    for (v, nm) in sorted.iter().zip(cpp_names.iter()) {
        let val_str = fmt_enum_value(v.value, &e.underlying);
        let tag = v.build_tag.unwrap_or("Windows 10 v20H2");
        let _ = writeln!(
            out,
            "        {nm:<w$} = {val_str},    // {tag}",
            nm = format!("{} ", nm),
            w = max_name + 1,
        );
    }
    let _ = writeln!(out, "    }};");
    let _ = write!(out, "{}", ns_close(&e.path.ns));
    out
}

// Render a [`TypeRef`] for the C++ side:
// - primitives use `uintN_t` / `intN_t` (no `u32`/`i32`)
// - bitfield underlying widths become `uintN_t` for arbitrary N
// - pointers collapse to `void*` (we don't carry pointee types in IR)
// - arrays render as `sdk::array<T, N>`
// - opaque storage renders as `uint8_t[N]` literally; user shouldn't see
//   these in practice (anon synthesis handles most cases)
//
fn render_cpp_type(t: &TypeRef) -> String {
    match t {
        TypeRef::Primitive(p) => primitive_to_cpp(p).to_owned(),
        TypeRef::Pointer => "void*".to_owned(),
        TypeRef::TypedPointer { path, kind, volatile_pointee } => {
            let kw = match kind {
                crate::ir::PointeeKind::Struct => "struct",
                crate::ir::PointeeKind::Union => "union",
                crate::ir::PointeeKind::Enum => "enum",
            };
            // `volatile` between type name and `*` qualifies the
            // pointee, not the pointer itself.
            let vol = if *volatile_pointee { " volatile" } else { "" };
            format!("{kw} {}::{}{vol}*", path.ns, path.name)
        },
        TypeRef::UserDefined(path) => format!("{}::{}", path.ns, path.name),
        TypeRef::External { cpp_path, .. } => (*cpp_path).to_owned(),
        TypeRef::Array { element, count } => {
            format!("sdk::array<{}, {}>", render_cpp_type(element), count)
        },
        TypeRef::Opaque(s) => format!("sdk::array<uint8_t, 0x{:x}>", s.max(&1)),
        // Pointer to a non-named pointee -- recurse and append `*`.
        TypeRef::Ref(inner) => format!("{}*", render_cpp_type(inner)),
        // Pointer to a function -- baked into the `sdk::function<R(args)>*` form.
        TypeRef::FnPtr(sig) => render_fn_ptr_cpp(sig),
        // Postfix `volatile`: `uint64_t volatile`. Wrapping `Ref`
        // yields `uint64_t volatile*` for PDB volatile fields like
        // `_KSPIN_LOCK_QUEUE.Lock`.
        TypeRef::Volatile(inner) => format!("{} volatile", render_cpp_type(inner)),
    }
}

// Render a field's *visible* C++ type, branching on bitfield (uses
// `uintN_t` of the field's actual bit_size, not the storage word).
// Strips the namespace prefix from any `UserDefined` reference matching
// the `inlined` set -- those types are declared *inside* the parent
// struct's scope, so the bare name is the only one that resolves at
// the field-declaration site.
//
fn render_field_type_cpp_scoped(
    f: &FieldDecl,
    inlined: &rustc_hash::FxHashSet<(String, String)>,
) -> String {
    if let Some(bf) = &f.bitfield {
        let prefix = if bf.signed { "int" } else { "uint" };
        return format!("{prefix}{}_t", f.bit_size.max(1));
    }
    if let TypeRef::UserDefined(p) = &f.ty
        && inlined.contains(&(p.ns.clone(), p.name.clone()))
    {
        return p.name.clone();
    }
    render_cpp_type(&f.ty)
}

fn primitive_to_cpp(p: &str) -> &'static str {
    match p {
        "char" => "char",
        "i8" => "int8_t",
        "u8" => "uint8_t",
        "i16" => "int16_t",
        "u16" => "uint16_t",
        "i32" => "int32_t",
        "u32" => "uint32_t",
        "wchar" => "wchar_t",
        "i64" => "int64_t",
        "u64" => "uint64_t",
        "i128" => "__int128",
        "u128" => "unsigned __int128",
        "f32" => "float",
        "f64" => "double",
        "::core::ffi::c_void" => "void",
        _ => "uint64_t",
    }
}

// Writes one `<target_ns>/api.hpp` plus its `magic/api.{start,end}.hpp`
// pair from an aggregated bucket of (public, hint_image, body_name)
// tuples collected across every MergedNamespace.  Called from
// `finalize_tree`, after all per-unit type emission completes.
//
// `hint_image` is carried per-public because the same `<target_ns>/api.hpp`
// can host symbols originating from multiple PDBs (e.g. `ki/api.hpp` gets
// `KiBugCheckData` from Wdf01000.sys AND `KiProcessorBlock` from
// ntoskrnl.exe).
fn write_api_bucket(
    include_root: &Path,
    target_ns: &str,
    items: &[(&crate::ir::PublicDecl, &'static str, String)],
) -> Result<()> {
    let ns_dir: PathBuf =
        target_ns.split("::").fold(include_root.to_path_buf(), |p, seg| p.join(seg));
    fs::create_dir_all(ns_dir.join("magic"))?;

    // Collect dependency type names referenced by public signatures
    // (function-pointer arg / return types).  Without these the
    // emitted `sdk::function<void(struct ex::push_lock_t*)>*` slots
    // would fail to compile because `ex::push_lock_t` is just a name
    // until the api.hpp pulls in its definition (or at minimum a
    // forward decl) from `ex/push_lock_t.hpp`.
    let mut fwds: Vec<(RustPath, crate::ir::PointeeKind)> = Vec::new();
    fn walk_typedptr(t: &TypeRef, out: &mut Vec<(RustPath, crate::ir::PointeeKind)>) {
        match t {
            TypeRef::TypedPointer { path, kind, .. } => out.push((path.clone(), *kind)),
            TypeRef::Array { element, .. } | TypeRef::Ref(element) => walk_typedptr(element, out),
            TypeRef::FnPtr(sig) => {
                walk_typedptr(&sig.return_type, out);
                for p in &sig.params {
                    walk_typedptr(p, out);
                }
            },
            _ => {},
        }
    }
    fn walk_userdef(t: &TypeRef, out: &mut Vec<RustPath>) {
        match t {
            TypeRef::UserDefined(p) => out.push(p.clone()),
            TypeRef::Array { element, .. } | TypeRef::Ref(element) => walk_userdef(element, out),
            TypeRef::FnPtr(sig) => {
                walk_userdef(&sig.return_type, out);
                for p in &sig.params {
                    walk_userdef(p, out);
                }
            },
            _ => {},
        }
    }
    let mut udefs: Vec<RustPath> = Vec::new();
    for (p, _, _) in items {
        if let Some(sig) = &p.signature {
            walk_typedptr(&TypeRef::FnPtr(Box::new(sig.clone())), &mut fwds);
            walk_userdef(&TypeRef::FnPtr(Box::new(sig.clone())), &mut udefs);
        }
    }
    fwds.sort_by(|a, b| a.0.ns.cmp(&b.0.ns).then(a.0.name.cmp(&b.0.name)));
    fwds.dedup_by(|a, b| a.0.ns == b.0.ns && a.0.name == b.0.name);
    udefs.sort_by(|a, b| a.ns.cmp(&b.ns).then(a.name.cmp(&b.name)));
    udefs.dedup_by(|a, b| a.ns == b.ns && a.name == b.name);
    // Emit FULL includes for every type referenced in a public's
    // signature -- both TypedPointer pointees and UserDefined
    // by-value -- so consumers dereferencing returned pointers see
    // a complete type, not a forward declaration. Stub headers
    // (from `inject_orphan_stubs`) satisfy the include without a
    // full definition. Same-namespace deps use a bare `"<name>.hpp"`
    // to avoid `-Wmicrosoft-include` under `-Werror`.
    let mut typed_deps: Vec<(String, String)> = Vec::new();
    for p in &udefs {
        typed_deps.push((p.ns.clone(), p.name.clone()));
    }
    for (path, _) in &fwds {
        typed_deps.push((path.ns.clone(), path.name.clone()));
    }
    typed_deps.sort();
    typed_deps.dedup();

    let mut body = String::new();
    let _ = writeln!(body, "// @generated by ntbindgen.  Do not edit.");
    let _ = writeln!(body, "// clang-format off");
    let _ = writeln!(body, "#pragma once");
    let _ = writeln!(body, "#include <ntbind/support_library.hpp>");
    let _ = writeln!(body);
    // Include full definitions for every referenced type (both
    // TypedPointer pointees and UserDefined embedded references).
    // Same-namespace deps get a bare relative include; cross-namespace
    // deps walk up to <include_root>/ntbind and back down.
    let depth = target_ns.split("::").count();
    let up_prefix: String = "../".repeat(depth);
    for (dep_ns, dep_name) in &typed_deps {
        if dep_ns == target_ns {
            let _ = writeln!(body, "#include \"{dep_name}.hpp\"");
        } else {
            let dep_dir: String = dep_ns.replace("::", "/");
            let _ = writeln!(body, "#include \"{up_prefix}{dep_dir}/{dep_name}.hpp\"");
        }
    }
    if !typed_deps.is_empty() {
        let _ = writeln!(body);
    }
    let _ = writeln!(body, "#include \"magic/api.start.hpp\"");
    let _ = write!(body, "{}", ns_open(target_ns));

    let mut start = String::new();
    let mut end = String::new();
    let _ = writeln!(start, "// @generated by ntbindgen.  Do not edit.");
    let _ = writeln!(start, "// clang-format off");
    let _ = writeln!(start, "#if !IN_PARSER");

    let mut used = rustc_hash::FxHashSet::default();
    let mut visible_index = 0u32;
    for (p, hint_image, body_name) in items {
        // Apply the same name transform as struct fields / enum variants:
        // unescape Rust-only keywords, then escape C++ keywords.  Without
        // this a public literally named `delete` / `new` / `class` / etc.
        // produces invalid C++ at the field-declaration site.
        let unescaped = cpp_unescape_rust_only_keyword(body_name).to_owned();
        let cpp_name_cow = cpp_escape_keyword(&unescaped);
        let mut name = cpp_name_cow.into_owned();
        while !used.insert(name.clone()) {
            name.push('_');
        }
        let _ = writeln!(body, "    // [{}]", p.original_name);
        let _ = writeln!(body, "    // Ldr = [{}]", hint_image);
        let _ = writeln!(body, "    // => Windows 10 v20H2");
        let _ = writeln!(body, "    // {} .rdata:0x{:x}, 0x10 bytes", hint_image, p.rva);
        let _ = writeln!(body, "    //");
        let public_ty = public_ty_cpp(p);
        let _ = writeln!(body, "    _m{vi}({public_ty}) {name};", vi = visible_index);
        let _ = writeln!(body);

        let _ = writeln!(
            start,
            "#define _m{vi}(...) _SDK_MAGIC_LINK(_SDK_ESCAPE(__VA_ARGS__), \"${orig}${img}\", 0x{rva:x}, 0x0, true, 0x{key:x}ULL)",
            vi = visible_index,
            orig = p.original_name,
            img = hint_image,
            rva = p.rva,
            key = p.key,
        );
        visible_index += 1;
    }
    let _ = write!(body, "{}", ns_close(target_ns));
    let _ = writeln!(body, "#include \"magic/api.end.hpp\"");

    let _ = writeln!(start, "#else");
    for i in 0..visible_index {
        let _ = writeln!(start, "#define _m{i}(...) __VA_ARGS__");
    }
    let _ = writeln!(start, "#endif");
    for i in 0..visible_index {
        let _ = writeln!(end, "#undef _m{i}");
    }
    let end = format!("// @generated by ntbindgen.  Do not edit.\n// clang-format off\n{end}");

    fs::write(ns_dir.join("api.hpp"), body)?;
    fs::write(ns_dir.join("magic").join("api.start.hpp"), start)?;
    fs::write(ns_dir.join("magic").join("api.end.hpp"), end)?;
    Ok(())
}

// Renders the type slot for `_m<N>(<TYPE>) name;` -- either a typed
// `sdk::function<R(args...)>*` recovered from the PDB's IPI stream, or
// the catch-all `sdk::unknown_ptr` when no signature is available.
//
// Unlike the Rust side, the C++ form CAN express variadics directly --
// `sdk::function<R(args..., ...)>*` Just Works under the C++ runtime
// types in `cpp/include/ntbind/runtime.hpp`.
fn public_ty_cpp(p: &crate::ir::PublicDecl) -> String {
    match &p.signature {
        Some(sig) => render_fn_ptr_cpp(sig),
        None => "sdk::unknown_ptr".to_owned(),
    }
}

// Renders a `FnSig` as a C++ `sdk::function<R(args...)>*` type.
fn render_fn_ptr_cpp(sig: &FnSig) -> String {
    let mut s = String::with_capacity(64);
    s.push_str("sdk::function<");
    s.push_str(&render_cpp_type(&sig.return_type));
    s.push('(');
    for (i, p) in sig.params.iter().enumerate() {
        if i != 0 {
            s.push_str(", ");
        }
        s.push_str(&render_cpp_type(p));
    }
    if sig.variadic {
        if !sig.params.is_empty() {
            s.push_str(", ");
        }
        s.push_str("...");
    }
    s.push_str(")>*");
    s
}
