//! Rust source emission.
//!
//! Generates a self-contained Cargo crate rooted at the `--out` path. The
//! crate's `src/lib.rs` re-exports every top-level namespace; each namespace
//! has a `mod.rs` that pulls in its own type files plus any nested
//! sub-namespaces. Per-PDB publics, when emitted, live in `<ns>/api.rs`.

use std::collections::BTreeMap;
use std::fmt::Write;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::emit::EmitOptions;
use crate::emit::common::{ty_path, upper_camel_case};
use crate::ir::{EnumDecl, FieldDecl, FnSig, PublicDecl, StructDecl, TypeDecl, TypeRef};
use crate::merge::MergedNamespace;
use crate::name::RustPath;

// Drives emission for one merged namespace. Writes the per-type files,
// per-namespace `mod.rs` chain, and (optionally) the publics `api.rs`. The
// crate-level `lib.rs` + `Cargo.toml` is written separately by
// `finalize_crate` after every namespace has landed on disk.
pub fn write_unit(ns: &MergedNamespace, out_root: &Path, opts: EmitOptions) -> Result<()> {
    let mut tree = NsTree::default();
    for ty in &ns.types {
        let path = ty_path(ty);
        tree.insert(&path.ns).types.push(ty);
    }
    if opts.publics && !ns.publics.is_empty() {
        tree.insert(ns.default_ns).publics_owner = true;
    }

    let src_root = out_root.join("src");
    fs::create_dir_all(&src_root)?;

    for ty in &ns.types {
        let (file_rel, body) = render_type(ty);
        let abs = src_root.join(&file_rel);
        if let Some(parent) = abs.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&abs, body).with_context(|| format!("writing {}", abs.display()))?;
    }
    if opts.publics && !ns.publics.is_empty() {
        write_api(&src_root, ns)?;
    }
    tree.write_mods(&src_root).context("writing per-namespace mod.rs files")?;
    Ok(())
}

// Writes the crate-level `lib.rs` listing every top-level namespace
// produced by the merger, plus the `Cargo.toml` manifest if absent.
pub fn finalize_crate(out_root: &Path, namespaces: &[MergedNamespace]) -> Result<()> {
    let src_root = out_root.join("src");
    fs::create_dir_all(&src_root)?;

    // Aggregate top-level namespace names across every merged namespace.
    let mut top_levels: std::collections::BTreeSet<String> = Default::default();
    for ns in namespaces {
        // Walk every emitted type path's top-level segment so sub-namespaces
        // also get a parent mod entry.
        for ty in &ns.types {
            let p = ty_path(ty);
            if let Some(seg) = p.ns.split("::").next() {
                top_levels.insert(seg.to_owned());
            }
        }
        if let Some(seg) = ns.default_ns.split("::").next() {
            top_levels.insert(seg.to_owned());
        }
    }

    let mut lib_rs = String::new();
    let _ = writeln!(lib_rs, "// @generated by ntbindgen.  Do not edit -- regenerate from PDBs.");
    let _ = writeln!(lib_rs);
    let _ =
        writeln!(lib_rs, "//! Windows kernel SDK -- regenerate from your PDBs with `ntbindgen`.");
    let _ = writeln!(lib_rs, "\n#![no_std]");
    let _ = writeln!(lib_rs, "#![allow(non_camel_case_types)]");
    let _ = writeln!(lib_rs, "#![allow(non_snake_case)]");
    let _ = writeln!(lib_rs, "#![allow(dead_code)]");
    let _ = writeln!(lib_rs, "#![allow(unused_imports)]");
    let _ = writeln!(lib_rs, "#![allow(unused_braces)]");
    let _ = writeln!(lib_rs, "#![allow(non_upper_case_globals)]");
    let _ = writeln!(lib_rs);
    for ns in &top_levels {
        let _ = writeln!(lib_rs, "pub mod {ns};");
    }
    fs::write(src_root.join("lib.rs"), lib_rs)?;

    let cargo_toml = out_root.join("Cargo.toml");
    if !cargo_toml.exists() {
        // The `ntbind` runtime crate's path. Users override with the
        // `NTBIND_CRATE_PATH` env var when emitting outside the workspace
        // (e.g. CI / doc-test tempdirs); the default works for the
        // `--out sdk` layout in this repo.
        let ntbind_path = std::env::var("NTBIND_CRATE_PATH")
            .unwrap_or_else(|_| "../crates/ntbind".to_owned())
            .replace('\\', "/");
        let manifest = format!(
            r#"[package]
name = "ntbind-sys"
version = "0.0.0"
edition = "2024"
publish = false
description = "Generated by ntbindgen. Do not edit by hand."

[lib]
path = "src/lib.rs"

[dependencies]
ntbind = {{ path = "{ntbind_path}" }}
"#
        );
        fs::write(&cargo_toml, manifest)?;
    }

    // Opt the generated crate out of formatting.  `disable_all_formatting`
    // makes rustfmt no-op every file it visits under this root; the
    // `@generated` markers each file carries hint the same to IDEs and
    // host tools (linguist, etc.).
    //
    fs::write(
        out_root.join("rustfmt.toml"),
        "# Generated by ntbindgen. Source is regenerated from PDBs; rustfmt\n\
         # has nothing useful to say about the layout.\n\
         disable_all_formatting = true\n",
    )?;
    Ok(())
}

#[derive(Default)]
struct NsNode<'a> {
    types: Vec<&'a TypeDecl>,
    children: BTreeMap<String, NsNode<'a>>,
    publics_owner: bool,
}

#[derive(Default)]
struct NsTree<'a> {
    root: NsNode<'a>,
}

impl<'a> NsTree<'a> {
    fn insert(&mut self, ns: &str) -> &mut NsNode<'a> {
        let mut node = &mut self.root;
        for seg in ns.split("::") {
            node = node.children.entry(seg.to_owned()).or_default();
        }
        node
    }

    fn write_mods(&self, src_root: &Path) -> Result<()> {
        for (name, child) in &self.root.children {
            write_node(src_root, name, child, ::std::slice::from_ref(name))?;
        }
        Ok(())
    }
}

fn write_node(src_root: &Path, name: &str, node: &NsNode<'_>, path: &[String]) -> Result<()> {
    let mut dir = src_root.to_path_buf();
    for seg in path {
        dir.push(seg);
    }
    fs::create_dir_all(&dir)?;

    let mut mod_rs = String::new();
    let _ = writeln!(mod_rs, "// @generated by ntbindgen.  Do not edit.");
    let _ = writeln!(mod_rs, "//!\n//! Namespace: `{}`\n", path.join("::"));

    // Type modules: files matching `<dir>/<name>.rs` other than `mod.rs` /
    // `api.rs`. We list them directly from the IR rather than scanning the
    // filesystem to keep generation deterministic.
    let mut type_modules: Vec<String> = node
        .types
        .iter()
        .map(|t| match t {
            TypeDecl::Struct(s) | TypeDecl::Union(s) => s.path.name.clone(),
            TypeDecl::Enum(e) => e.path.name.clone(),
            TypeDecl::Stub(s) => s.path.name.clone(),
        })
        .collect();
    type_modules.sort();
    type_modules.dedup();

    for m in &type_modules {
        let _ = writeln!(mod_rs, "pub mod {m};");
    }
    if !type_modules.is_empty() {
        let _ = writeln!(mod_rs);
        for m in &type_modules {
            let _ = writeln!(mod_rs, "pub use {m}::*;");
        }
    }

    // Nested namespaces.
    if !node.children.is_empty() {
        let _ = writeln!(mod_rs);
        for child_name in node.children.keys() {
            let _ = writeln!(mod_rs, "pub mod {child_name};");
        }
    }

    // Publics live in `api.rs` for the owning namespace.
    if node.publics_owner {
        let _ = writeln!(mod_rs, "\npub mod api;");
    }

    // Prelude -- re-exports every type in this namespace under a single
    // glob target so consumers can `use crate::<ns>::prelude::*;` instead
    // of importing each type one by one. Anonymous nested types (`u<N>_..`)
    // are excluded since they're rarely referenced directly.
    let prelude_modules: Vec<&String> =
        type_modules.iter().filter(|m| !is_anon_module_name(m)).collect();
    if !prelude_modules.is_empty() {
        let _ = writeln!(mod_rs);
        let _ = writeln!(mod_rs, "/// Re-exports every named type in this namespace.");
        let _ = writeln!(mod_rs, "///");
        let _ = writeln!(mod_rs, "/// ```ignore");
        let _ = writeln!(mod_rs, "/// use crate::{}::prelude::*;", path.join("::"));
        let _ = writeln!(mod_rs, "/// ```");
        let _ = writeln!(mod_rs, "pub mod prelude {{");
        for m in &prelude_modules {
            let _ = writeln!(mod_rs, "    pub use super::{m}::*;");
        }
        let _ = writeln!(mod_rs, "}}");
    }

    let _ = name;
    fs::write(dir.join("mod.rs"), mod_rs)?;

    // Recurse.
    for (child_name, child_node) in &node.children {
        let mut next = path.to_vec();
        next.push(child_name.clone());
        write_node(src_root, child_name, child_node, &next)?;
    }

    // Anonymous-nested type module names look like `<parent>_u<N>_<field>_t`.
    // The prelude skips them so `use ns::prelude::*` doesn't pull a wall of
    // `u0_..`/`u1_..` symbols into the user's scope.
    //
    // True if `name` contains a `_u<digit>` substring -- the
    // synthetic-anon marker injected by `synthesize_anonymous`.
    // Scans past any `_u<non-digit>` occurrences (PDB stems can carry
    // `_unmask`, `_user`, ...) and only returns once it has seen the
    // digit-bearing form.
    //
    fn is_anon_module_name(name: &str) -> bool {
        let mut from = 0usize;
        while let Some(rel) = name[from..].find("_u") {
            let pos = from + rel;
            if name[pos + 2..].starts_with(|c: char| c.is_ascii_digit()) {
                return true;
            }
            from = pos + 2;
        }
        false
    }

    Ok(())
}

fn render_type(t: &TypeDecl) -> (PathBuf, String) {
    match t {
        TypeDecl::Struct(s) => (file_path(&s.path), render_struct(s, /* is_union = */ false)),
        TypeDecl::Union(s) => (file_path(&s.path), render_struct(s, /* is_union = */ true)),
        TypeDecl::Enum(e) => (file_path(&e.path), render_enum(e)),
        TypeDecl::Stub(s) => (file_path(&s.path), render_stub(s)),
    }
}

// Emit a stub type -- a minimal `pub struct CamelName(PhantomData<()>);`
// that lets typed-pointer references resolve when the kernel never
// exposes a full TPI definition. PhantomData ensures the user can't
// accidentally construct an instance.
//
fn render_stub(s: &crate::ir::StubDecl) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// @generated by ntbindgen.  Do not edit.");
    let _ = writeln!(out, "//!\n//! Opaque kernel pointee -- referenced only via");
    let _ = writeln!(
        out,
        "//! `*mut crate::{}::{}` in other types. The kernel doesn't expose",
        s.path.ns,
        upper_camel_case(&s.path.name)
    );
    let _ = writeln!(out, "//! a full definition in user-side PDBs.");
    let _ = writeln!(out);
    let camel = upper_camel_case(&s.path.name);
    let _ = writeln!(out, "/// Opaque pointee -- see module-level docs.");
    let _ = writeln!(out, "#[repr(transparent)]");
    let _ = writeln!(out, "#[non_exhaustive]");
    let _ = writeln!(out, "pub struct {camel}(::core::marker::PhantomData<()>);");
    out
}

fn file_path(p: &RustPath) -> PathBuf {
    let mut path = PathBuf::new();
    for seg in p.ns.split("::") {
        path.push(seg);
    }
    path.push(format!("{}.rs", p.name));
    path
}

fn render_struct(s: &StructDecl, is_union: bool) -> String {
    let mut out = String::new();
    let kw = if is_union { "union" } else { "struct" };
    let _ = writeln!(out, "// @generated by ntbindgen.  Do not edit.");
    let _ = writeln!(
        out,
        "//!\n//! `{kw} {orig}` -- {size} bytes.",
        kw = kw,
        orig = s.original_name,
        size = s.size
    );
    let _ = writeln!(out, "\nuse ntbind as _ntbind;");
    let camel = upper_camel_case(&s.path.name);
    let size = s.size.max(1);

    // Pre-pass: compute each field's rendered type. Any one over the
    // long-name limit gets a module-level alias (`<field>_t`) so the
    // accessor signature stays short.
    let mut aliases: Vec<(String, String)> = Vec::new(); // (alias_name, ty_text)
    let mut field_ty_overrides: Vec<Option<String>> = Vec::with_capacity(s.fields.len());
    for f in &s.fields {
        let raw = render_type_ref(&f.ty);
        if raw.chars().count() > LONG_NAME_LIMIT {
            let alias = format!("{}_t", f.rust_name);
            aliases.push((alias.clone(), raw));
            field_ty_overrides.push(Some(alias));
        } else {
            field_ty_overrides.push(None);
        }
    }

    if !aliases.is_empty() {
        let _ = writeln!(out);
        for (alias, ty) in &aliases {
            let _ = writeln!(
                out,
                "/// Shortened alias for `{camel}.{alias}` (>{LONG_NAME_LIMIT} chars when inlined)."
            );
            let _ = writeln!(out, "pub type {alias} = {ty};");
        }
    }
    let _ = writeln!(out);
    let _ = writeln!(out, "/// `{}` (PDB original: `{}`).", camel, s.original_name);
    let _ = writeln!(out, "///");
    let _ = writeln!(out, "/// Opaque byte storage -- instances come from the kernel; user code");
    let _ = writeln!(out, "/// never constructs them directly. `#[non_exhaustive]` enforces that");
    let _ = writeln!(out, "/// boundary at the type level.");
    let _ = writeln!(out, "#[repr(C)]");
    let _ = writeln!(out, "#[non_exhaustive]");
    let _ = writeln!(out, "pub struct {camel} {{");
    let _ = writeln!(out, "    _raw: [u8; 0x{size:x}],");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "// SAFETY: PDB-defined kernel structs are POD; the kernel itself owns");
    let _ = writeln!(out, "// synchronization. We give Send + Sync so users can stash `&{camel}`");
    let _ = writeln!(out, "// (and raw pointers) in cross-thread containers without `unsafe impl`");
    let _ = writeln!(out, "// boilerplate at every call site.");
    let _ = writeln!(out, "unsafe impl ::core::marker::Send for {camel} {{}}");
    let _ = writeln!(out, "unsafe impl ::core::marker::Sync for {camel} {{}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "impl ::core::fmt::Debug for {camel} {{");
    let _ = writeln!(
        out,
        "    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {{"
    );
    let _ = writeln!(out, "        f.debug_struct(\"{camel}\")");
    let _ = writeln!(out, "            .field(\"size\", &Self::SIZE)");
    let _ = writeln!(out, "            .finish_non_exhaustive()");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "impl {camel} {{");
    let _ = writeln!(out, "    /// Canonical byte size from the PDB.");
    let _ = writeln!(out, "    pub const SIZE: usize = 0x{size:x};");
    let _ = writeln!(out);
    let _ = writeln!(out, "    /// Memory layout (size + alignment) of the canonical-build form.");
    let _ = writeln!(out, "    pub const LAYOUT: ::core::alloc::Layout =");
    let _ = writeln!(
        out,
        "        unsafe {{ ::core::alloc::Layout::from_size_align_unchecked(Self::SIZE, ::core::mem::align_of::<Self>()) }};"
    );
    let _ = writeln!(out);
    // Build a name-occupancy count: every field's accessor name (always)
    // plus every Copy-primitive's companion names (read_/write_/
    // read_volatile_/write_volatile_). If any name appears more than once,
    // we suppress the companions involved so the impl block stays free of
    // duplicate definitions.
    use std::collections::HashMap;
    let mut name_counts: HashMap<String, u32> = HashMap::new();
    for f in &s.fields {
        *name_counts.entry(f.rust_name.clone()).or_default() += 1;
        if is_value_copyable(&f.ty) {
            for prefix in ["read_", "write_", "read_volatile_", "write_volatile_"] {
                *name_counts.entry(format!("{prefix}{}", f.rust_name)).or_default() += 1;
            }
        }
    }
    let occupied: rustc_hash::FxHashSet<String> =
        name_counts.iter().filter(|(_, n)| **n > 1).map(|(k, _)| k.clone()).collect();
    for (f, override_ty) in s.fields.iter().zip(field_ty_overrides.iter()) {
        emit_field(&mut out, &s.original_name, f, override_ty.as_deref(), &occupied);
    }
    let _ = writeln!(out, "}}");

    let summary_key = s.summary_key;
    let _ = writeln!(out);
    let _ = writeln!(out, "_ntbind::struct_summary! {{");
    let _ = writeln!(out, "    identifier = b\"{}.$\\0\",", s.original_name);
    let _ = writeln!(out, "    byte_size = 0x{size:x},");
    let _ = writeln!(out, "    exists = true,");
    let _ = writeln!(out, "    key = 0x{summary_key:x}u64,");
    let _ = writeln!(out, "}}");

    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "const _: () = assert!(\n    ::core::mem::size_of::<{camel}>() == {camel}::SIZE,\n    \"ntbindgen: canonical size mismatch -- regenerate the SDK against the matching PDBs\",\n);",
    );
    // The struct's `_raw` field is private but unused -- silence the lint;
    // declaring `_raw` is the storage's `repr(C)` width.
    let _ = writeln!(out, "\n#[allow(dead_code)]");
    let _ = writeln!(
        out,
        "const _USED: ::core::marker::PhantomData<{camel}> = ::core::marker::PhantomData;"
    );
    out
}

// Long-name limit (chars).
const LONG_NAME_LIMIT: usize = 48;

fn emit_field(
    out: &mut String,
    parent_original: &str,
    f: &FieldDecl,
    override_ty: Option<&str>,
    field_name_set: &rustc_hash::FxHashSet<String>,
) {
    let ty_rendered = match override_ty {
        Some(alias) => alias.to_owned(),
        None => render_type_ref(&f.ty),
    };

    // Skip checks first so we don't emit a `///` doc-block that has no
    // following item to attach to.
    if f.bit_size == 0 {
        let _ = writeln!(
            out,
            "    // `{}.{}` -- zero-width; documented only.",
            parent_original, f.original_name
        );
        return;
    }
    if f.bitfield.is_none() && (!f.bit_offset.is_multiple_of(8) || !f.bit_size.is_multiple_of(8)) {
        let _ = writeln!(
            out,
            "    // `{}.{}` -- misaligned non-bitfield; raw bytes via `.as_ptr()`.",
            parent_original, f.original_name
        );
        return;
    }

    // Doc-block: PDB context + per-build offset table (when multi-build).
    let _ = writeln!(
        out,
        "    /// `{}.{}` -- canonical byte offset `0x{:x}`, {} bits wide.",
        parent_original,
        f.original_name,
        f.bit_offset / 8,
        f.bit_size
    );
    if !f.per_build.is_empty() {
        let _ = writeln!(out, "    ///");
        let _ = writeln!(out, "    /// | Build | Byte offset |");
        let _ = writeln!(out, "    /// |---|---|");
        for (build, off) in &f.per_build {
            if *off == u32::MAX {
                let _ = writeln!(out, "    /// | `{build}` | *absent* |");
            } else {
                let _ = writeln!(out, "    /// | `{build}` | `0x{off:x}` |");
            }
        }
    }

    // Per-field canonical-offset and size constants. Available to code that
    // wants to operate against a fixed layout without going through the
    // runtime symbol-table lookup.
    let off_const = format!("{}_OFFSET", f.rust_name.to_ascii_uppercase());
    let size_const = format!("{}_BIT_SIZE", f.rust_name.to_ascii_uppercase());
    let _ = writeln!(out, "    pub const {off_const}: usize = 0x{:x};", f.bit_offset / 8);
    let _ = writeln!(out, "    pub const {size_const}: u16 = {};", f.bit_size);

    // Bitfield path -- PDB carried explicit storage size and signedness.
    if let Some(bf) = &f.bitfield {
        let _ = writeln!(out, "    _ntbind::bit_field! {{");
        let _ = writeln!(out, "        name = {name},", name = f.rust_name);
        let _ = writeln!(out, "        setter = set_{name},", name = f.rust_name);
        let _ = writeln!(out, "        ty = {ty_rendered},");
        let _ =
            writeln!(out, "        identifier = b\"{parent_original}.{}\\0\",", f.original_name);
        let _ = writeln!(out, "        offset_bits = {},", f.bit_offset);
        let _ = writeln!(out, "        size_bits = {},", f.bit_size);
        let _ = writeln!(out, "        storage_bytes = {},", bf.storage_bytes);
        let _ = writeln!(out, "        signed = {},", bf.signed);
        let _ = writeln!(out, "        exists = true,");
        let _ = writeln!(out, "        key = 0x{:x}u64,", f.key);
        let _ = writeln!(out, "    }}\n");
        return;
    }
    let _ = writeln!(out, "    _ntbind::field! {{");
    let _ = writeln!(out, "        name = {},", f.rust_name);
    let _ = writeln!(out, "        ty = {ty_rendered},");
    let _ = writeln!(out, "        identifier = b\"{parent_original}.{}\\0\",", f.original_name);
    let _ = writeln!(out, "        offset_bits = {},", f.bit_offset);
    let _ = writeln!(out, "        size_bits = {},", f.bit_size);
    let _ = writeln!(out, "        exists = true,");
    let _ = writeln!(out, "        key = 0x{:x}u64,", f.key);
    let _ = writeln!(out, "    }}");

    // Companion value accessors for Copy primitives -- saves the user from
    // `unsafe { *foo.bar() }` chains. Uses `read_unaligned`/`write_unaligned`
    // because the canonical struct alignment is 1.
    // Only emit when no companion name is occupied (would collide with a
    // sibling field's accessor or another field's companion).
    let read_name = format!("read_{}", f.rust_name);
    let write_name = format!("write_{}", f.rust_name);
    let read_vol_name = format!("read_volatile_{}", f.rust_name);
    let write_vol_name = format!("write_volatile_{}", f.rust_name);
    let collision = field_name_set.contains(&read_name)
        || field_name_set.contains(&write_name)
        || field_name_set.contains(&read_vol_name)
        || field_name_set.contains(&write_vol_name);
    if is_value_copyable(&f.ty) && !collision {
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "    /// Read [`Self::{}`] by value (unaligned, non-volatile).",
            f.rust_name
        );
        let _ = writeln!(out, "    ///");
        let _ = writeln!(out, "    /// # Safety");
        let _ = writeln!(out, "    /// `&self` must point at storage the kernel populated;");
        let _ = writeln!(out, "    /// alignment is not assumed.");
        let _ = writeln!(out, "    #[inline]");
        let _ = writeln!(
            out,
            "    pub unsafe fn read_{name}(&self) -> {ty} {{ unsafe {{ ::core::ptr::read_unaligned(self.{name}()) }} }}",
            name = f.rust_name,
            ty = ty_rendered
        );
        let _ = writeln!(
            out,
            "    /// Write [`Self::{}`] by value (unaligned, non-volatile).",
            f.rust_name
        );
        let _ = writeln!(out, "    ///");
        let _ = writeln!(out, "    /// # Safety");
        let _ = writeln!(out, "    /// Caller must hold a unique reference to storage and respect");
        let _ =
            writeln!(out, "    /// any kernel synchronization invariants for the target field.");
        let _ = writeln!(out, "    #[inline]");
        let _ = writeln!(
            out,
            "    pub unsafe fn write_{name}(&mut self, value: {ty}) {{ unsafe {{ ::core::ptr::write_unaligned(self.{name}() as *mut {ty}, value) }} }}",
            name = f.rust_name,
            ty = ty_rendered
        );

        // Volatile companions -- for fields the kernel mutates while we
        // read (`KUSER_SHARED_DATA.SystemTime`, `KPCR.Self`, etc.).
        // Byte-by-byte volatile loads/stores keep semantics correct on any
        // alignment.
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "    /// Volatile read of [`Self::{}`] -- use for kernel-racing fields.",
            f.rust_name
        );
        let _ = writeln!(out, "    ///");
        let _ = writeln!(out, "    /// # Safety");
        let _ = writeln!(
            out,
            "    /// Same invariants as [`Self::read_{}`] plus: the kernel must keep",
            f.rust_name
        );
        let _ = writeln!(out, "    /// the field's storage live across the load.");
        let _ = writeln!(out, "    #[inline]");
        let _ = writeln!(
            out,
            "    pub unsafe fn read_volatile_{name}(&self) -> {ty} {{ unsafe {{ _ntbind::__macro_support::read_volatile_bytes::<{ty}>(self.{name}() as *const u8) }} }}",
            name = f.rust_name,
            ty = ty_rendered
        );
        let _ = writeln!(out, "    /// Volatile write of [`Self::{}`].", f.rust_name);
        let _ = writeln!(out, "    ///");
        let _ = writeln!(out, "    /// # Safety");
        let _ = writeln!(out, "    /// Same invariants as [`Self::write_{}`].", f.rust_name);
        let _ = writeln!(out, "    #[inline]");
        let _ = writeln!(
            out,
            "    pub unsafe fn write_volatile_{name}(&mut self, value: {ty}) {{ unsafe {{ _ntbind::__macro_support::write_volatile_bytes::<{ty}>(self.{name}() as *mut u8, value) }} }}",
            name = f.rust_name,
            ty = ty_rendered
        );
    }
    let _ = writeln!(out);
}

// True iff a TypeRef is a Copy primitive worth generating `read_*`/`write_*`
// companions for. Everything else (pointers, opaque storage, arrays, user
// types) keeps the raw-pointer accessor path only.
//
fn is_value_copyable(t: &TypeRef) -> bool {
    matches!(
        t,
        TypeRef::Primitive(p) if matches!(
            *p,
            "u8" | "u16" | "u32" | "u64" | "u128"
                | "i8" | "i16" | "i32" | "i64" | "i128"
                | "f32" | "f64" | "usize" | "isize"
        )
    )
}

fn render_enum(e: &EnumDecl) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// @generated by ntbindgen.  Do not edit.");
    let _ = writeln!(out, "//!\n//! `enum {}` (PDB).", e.original_name);
    let underlying = render_type_ref(&e.underlying);
    let camel = upper_camel_case(&e.path.name);
    let _ = writeln!(out, "\n#[repr({underlying})]");
    let _ = writeln!(out, "#[derive(Clone, Copy, Debug, PartialEq, Eq)]");
    let _ = writeln!(out, "pub enum {camel} {{");

    // First pass: emit one variant per unique (value, name) combination.
    // Aliases are deferred to `impl` consts because Rust forbids duplicate
    // discriminants on `enum`.
    let mut seen_values = rustc_hash::FxHashSet::default();
    let mut aliases: Vec<(String, &str, i128)> = Vec::new();
    for v in &e.variants {
        let var_name = upper_camel_case(&v.rust_name);
        if seen_values.insert(v.value) {
            let _ = writeln!(out, "    /// `{}` = 0x{:x}", v.original_name, v.value);
            let _ = writeln!(out, "    {var_name} = {} as _,", v.value);
        } else {
            aliases.push((var_name, &v.original_name, v.value));
        }
    }
    let _ = writeln!(out, "}}");

    if !aliases.is_empty() {
        let _ = writeln!(out);
        let _ = writeln!(out, "impl {camel} {{");
        for (alias, orig, value) in &aliases {
            // The alias points at the primary variant carrying the same value.
            let primary = e
                .variants
                .iter()
                .find(|x| x.value == *value)
                .map(|x| upper_camel_case(&x.rust_name))
                .unwrap_or_else(|| alias.clone());
            let _ = writeln!(out, "    /// Alias for `{}` (PDB: `{orig}`).", primary);
            let _ = writeln!(
                out,
                "    pub const {alias}: Self = Self::{primary};",
                alias = alias,
                primary = primary
            );
        }
        let _ = writeln!(out, "}}");
    }

    // `TryFrom<underlying>` -- recover the enum from a raw kernel-supplied
    // integer. Returns Err with the unrecognized value so callers can log /
    // pass through. The matched variants list every distinct discriminant
    // (aliases share a value and resolve to the first-seen primary).
    let _ = writeln!(out);
    let _ = writeln!(out, "impl ::core::convert::TryFrom<{underlying}> for {camel} {{");
    let _ =
        writeln!(out, "    type Error = ::ntbind::error::UnknownDiscriminant<Self, {underlying}>;");
    let _ = writeln!(
        out,
        "    fn try_from(value: {underlying}) -> ::core::result::Result<Self, ::ntbind::error::UnknownDiscriminant<Self, {underlying}>> {{"
    );
    let _ = writeln!(out, "        match value {{");
    let mut emitted_values = rustc_hash::FxHashSet::default();
    for v in &e.variants {
        if !emitted_values.insert(v.value) {
            continue;
        }
        let var_name = upper_camel_case(&v.rust_name);
        let _ = writeln!(
            out,
            "            {value} => ::core::result::Result::Ok(Self::{var_name}),",
            value = v.value,
        );
    }
    let _ = writeln!(
        out,
        "            other => ::core::result::Result::Err(::ntbind::error::UnknownDiscriminant::new(other)),"
    );
    let _ = writeln!(out, "        }}");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
    out
}

fn render_type_ref(t: &TypeRef) -> String {
    match t {
        TypeRef::Pointer => "*mut ::core::ffi::c_void".to_owned(),
        TypeRef::Primitive(p) => (*p).to_owned(),
        TypeRef::TypedPointer { path, .. } => {
            let camel = upper_camel_case(&path.name);
            format!("*mut crate::{ns}::{camel}", ns = path.ns)
        },
        TypeRef::UserDefined(path) => {
            let camel = upper_camel_case(&path.name);
            format!("crate::{ns}::{camel}", ns = path.ns)
        },
        TypeRef::Array { element, count } => format!("[{}; {}]", render_type_ref(element), count),
        TypeRef::Opaque(s) => format!("[u8; 0x{:x}]", s.max(&1)),
        TypeRef::External { rust_path, .. } => (*rust_path).to_owned(),
        // Pointer to a non-user-defined pointee -- recurse and prefix
        // `*mut`.  Closes the primitive-pointer / pointer-to-pointer
        // fidelity gap vs Selene.
        TypeRef::Ref(inner) => format!("*mut {}", render_type_ref(inner)),
        // Pointer to a function -- Rust fn pointers are already
        // pointer-sized values at the language level; no outer `*mut`.
        TypeRef::FnPtr(sig) => render_fn_ptr_rust(sig),
    }
}

fn write_api(src_root: &Path, unit: &MergedNamespace) -> Result<()> {
    let ns_path: PathBuf =
        unit.default_ns.split("::").fold(src_root.to_path_buf(), |p, seg| p.join(seg));
    fs::create_dir_all(&ns_path)?;

    let mut body = String::new();
    let _ = writeln!(body, "// @generated by ntbindgen.  Do not edit.");
    let _ = writeln!(body, "//!\n//! Publics for namespace `{}`.\n", unit.default_ns);
    let _ = writeln!(body, "use ntbind as _ntbind;");
    let _ = writeln!(body, "use _ntbind::public::Public;\n");

    let mut used = rustc_hash::FxHashSet::default();
    for p in &unit.publics {
        let mut name = p.rust_name.clone();
        while !used.insert(name.clone()) {
            name.push('_');
        }
        emit_public(&mut body, &name, p, unit.hint_image);
    }

    fs::write(ns_path.join("api.rs"), body)?;
    Ok(())
}

fn emit_public(out: &mut String, name: &str, p: &PublicDecl, hint_image: &str) {
    let ty_str = public_ty_rust(p);
    let _ = writeln!(out, "/// `{}` -- RVA 0x{:x}.", p.original_name, p.rva);
    let _ = writeln!(out, "#[inline]");
    let _ = writeln!(out, "pub fn {name}() -> Public<{ty_str}> {{ _ntbind::public! {{");
    let _ = writeln!(out, "    name = __inner,");
    let _ = writeln!(out, "    ty = {ty_str},");
    let _ = writeln!(out, "    identifier = b\"${}${}\\0\",", p.original_name, hint_image);
    let _ = writeln!(out, "    rva_hint = 0x{:x},", p.rva);
    let _ = writeln!(out, "    syscall_idx = 0,");
    let _ = writeln!(out, "    exists = true,");
    let _ = writeln!(out, "    key = 0x{:x}u64,", p.key);
    let _ = writeln!(out, "}} __inner() }}\n");
}

// Renders the `T` for `Public<T>` -- either a typed function pointer
// recovered from the PDB's IPI stream, or the legacy `c_void` fallback
// when no signature is available (or the signature is variadic, which
// Rust cannot express as a function-pointer type).
fn public_ty_rust(p: &PublicDecl) -> String {
    match &p.signature {
        Some(sig) if !sig.variadic => render_fn_ptr_rust(sig),
        _ => "::core::ffi::c_void".to_owned(),
    }
}

// Renders a non-variadic `FnSig` as a Rust function-pointer type.
// Always `unsafe extern "system" fn(...) -> ret` -- every NT public is
// `unsafe` to call (kernel address, no Rust-side invariants), and the
// Microsoft x64 ABI is what `extern "system"` selects on Win64.
fn render_fn_ptr_rust(sig: &FnSig) -> String {
    let mut s = String::with_capacity(64);
    s.push_str("unsafe extern \"system\" fn(");
    for (i, p) in sig.params.iter().enumerate() {
        if i != 0 {
            s.push_str(", ");
        }
        s.push_str(&render_type_ref(p));
    }
    s.push(')');
    // Elide the `-> ()` for void returns to match what the user would
    // hand-write, and to keep the type-string short in the macro arg.
    let ret = render_type_ref(&sig.return_type);
    if ret != "::core::ffi::c_void" {
        s.push_str(" -> ");
        s.push_str(&ret);
    }
    s
}
