// One Windows build the generator ingests. Multi-build merging produces
// canonical types from the build marked `is_canonical = true`;
// intermediate builds contribute per-field offset comments. With a
// single entry the canonical flag is irrelevant.
//
#[derive(Clone, Copy, Debug)]
pub struct BuildEntry {
    // Short tag shown in per-build comments and per-build suffix renames.
    pub name: &'static str,
    // Subdirectory of `--symbols` holding this build's PDBs.  Empty
    // string -> the PDBs sit directly under `--symbols`.
    pub path_suffix: &'static str,
    // True for the build whose layout the generator bakes as the
    // in-source default.  Exactly one entry sets this.
    pub is_canonical: bool,
    // Human-readable Windows release tag used in per-variant / per-field
    // comments (e.g. "Windows 10 v20H2").
    pub friendly: &'static str,
}

// Build inventory.  Each entry's `path_suffix` is searched under
// `--symbols`; missing entries are skipped with a warning instead of
// failing the whole run.  Extend this slice when adding cross-build
// merging back in.
pub const BUILDS: &[BuildEntry] = &[BuildEntry {
    name: "host",
    path_suffix: "",
    is_canonical: true,
    friendly: "Windows 10 v20H2",
}];

// One PDB to scrape and its Rust namespace.
#[derive(Clone, Copy, Debug)]
pub struct PdbEntry {
    // Rust module name. Multiple entries may share a tag (e.g. several PDBs
    // all contribute to `nt`); the generator merges them.
    pub ns_tag: &'static str,
    // PDB file name relative to `--symbols`.
    pub path: &'static str,
    // Hint image for resolving publics through the patcher
    // (`$<Name>$<image>` identifier convention).
    pub hint_image: &'static str,
}

// Order of preference when a type appears in multiple PDBs. Earlier entries win.
pub const PDB_ENTRIES: &[PdbEntry] = &[
    PdbEntry { ns_tag: "nt", path: "ntkrnlmp.pdb", hint_image: "ntoskrnl.exe" },
    PdbEntry { ns_tag: "nt", path: "hal.pdb", hint_image: "hal.dll" },
    PdbEntry { ns_tag: "ci", path: "ci.pdb", hint_image: "ci.dll" },
    PdbEntry { ns_tag: "kuser", path: "win32kfull.pdb", hint_image: "win32kfull.sys" },
    PdbEntry { ns_tag: "kuser", path: "win32kbase.pdb", hint_image: "win32kbase.sys" },
    PdbEntry { ns_tag: "kuser", path: "win32k.pdb", hint_image: "win32k.sys" },
    PdbEntry { ns_tag: "wuser", path: "win32u.pdb", hint_image: "win32u.dll" },
    PdbEntry { ns_tag: "wuser", path: "user32.pdb", hint_image: "user32.dll" },
    PdbEntry { ns_tag: "pci", path: "pci.pdb", hint_image: "pci.sys" },
    PdbEntry { ns_tag: "mou", path: "mouclass.pdb", hint_image: "mouclass.sys" },
    PdbEntry { ns_tag: "kbd", path: "kbdclass.pdb", hint_image: "kbdclass.sys" },
    PdbEntry { ns_tag: "hid", path: "hidclass.pdb", hint_image: "hidclass.sys" },
    PdbEntry { ns_tag: "ndis", path: "ndis.pdb", hint_image: "ndis.sys" },
    PdbEntry { ns_tag: "stor::ahci", path: "storahci.pdb", hint_image: "storahci.sys" },
    PdbEntry { ns_tag: "stor::nvme", path: "stornvme.pdb", hint_image: "stornvme.sys" },
    PdbEntry { ns_tag: "stor::port", path: "storport.pdb", hint_image: "storport.sys" },
    PdbEntry { ns_tag: "scsi", path: "scsiport.pdb", hint_image: "scsiport.sys" },
    PdbEntry { ns_tag: "ata", path: "ataport.pdb", hint_image: "ataport.sys" },
    PdbEntry { ns_tag: "atapi", path: "atapi.pdb", hint_image: "atapi.sys" },
    PdbEntry { ns_tag: "fltmgr", path: "fltMgr.pdb", hint_image: "fltMgr.sys" },
    PdbEntry { ns_tag: "disk", path: "disk.pdb", hint_image: "disk.sys" },
    PdbEntry { ns_tag: "afd", path: "afd.pdb", hint_image: "afd.sys" },
    PdbEntry { ns_tag: "netio", path: "netio.pdb", hint_image: "netio.sys" },
    PdbEntry { ns_tag: "tdi", path: "tdi.pdb", hint_image: "tdi.sys" },
    PdbEntry { ns_tag: "tcp", path: "tcpip.pdb", hint_image: "tcpip.sys" },
    PdbEntry { ns_tag: "dxgk", path: "dxgkrnl.pdb", hint_image: "dxgkrnl.sys" },
    PdbEntry { ns_tag: "dxgmms2", path: "dxgmms2.pdb", hint_image: "dxgmms2.sys" },
    PdbEntry { ns_tag: "dxgi", path: "dxgi.pdb", hint_image: "dxgi.dll" },
    PdbEntry { ns_tag: "ntdll", path: "ntdll.pdb", hint_image: "ntdll.dll" },
    PdbEntry { ns_tag: "wdf", path: "Wdf01000.pdb", hint_image: "Wdf01000.sys" },
    PdbEntry { ns_tag: "wdfilter", path: "WdFilter.pdb", hint_image: "WdFilter.sys" },
    PdbEntry { ns_tag: "win", path: "combase.pdb", hint_image: "combase.dll" },
];

// PDB namespace prefix -> module path translation
// (`_KI_FOO` -> `(ki, foo)`).  Longest match wins.
pub const NAMESPACE_PREFIXES: &[(&str, &str)] = &[
    // Multi-character prefixes (longest first so they match before short ones).
    ("event_trace", "etwi"),
    // "Private" prefixes (suffix `p`, `pf`, etc.) -- inserted first so
    // they win over their shorter-substring siblings (`iop` before `io`,
    // `halp` before `hal`, ...). classify() returns on first match.
    ("dbgkp", "dbgkp"),
    ("ndisp", "ndisp"),
    ("iopf", "iopf"),
    ("iovp", "iovp"),
    ("ksep", "ksep"),
    ("hdlsp", "hdlsp"),
    ("rtlpx", "rtlpx"),
    ("expi", "expi"),
    ("etwp", "etwp"),
    ("halp", "halp"),
    ("hali", "hali"),
    ("hvlp", "hvlp"),
    ("hvi", "hvi"),
    ("hvp", "hvp"),
    ("ldrp", "ldrp"),
    ("lpcp", "lpcp"),
    ("rtlp", "rtlp"),
    ("rtlx", "rtlx"),
    ("wmip", "wmip"),
    ("popp", "popp"),
    ("sdbp", "sdbp"),
    ("verfp", "verfp"),
    ("hidp", "hidp"),
    ("alpcp", "alpcp"),
    ("alpci", "alpci"),
    ("bapdp", "bapdp"),
    ("arbp", "arbp"),
    ("bgkp", "bgkp"),
    ("bipd", "bipd"),
    ("aslp", "aslp"),
    ("ahci", "ahci"),
    ("csrp", "csrp"),
    ("dmrp", "dmrp"),
    ("drvp", "drvp"),
    ("dbgp", "dbgp"),
    ("emp", "emp"),
    ("gxp", "gxp"),
    // Special-case: `exp` maps directly to `expi` so `_EXP_FOO` lands in
    // `expi::foo_t` rather than `ex::p::foo_t`.
    ("exp", "expi"),
    ("iov", "iov"),
    ("iop", "iop"),
    ("obp", "obp"),
    ("cmp", "cmp"),
    ("cip", "cip"),
    ("civ", "civ"),
    ("psp", "psp"),
    ("pcix", "pcix"),
    ("pip", "pip"),
    ("pix", "pix"),
    ("pii", "pii"),
    ("pfp", "pfp"),
    ("pfx", "pfx"),
    ("pox", "pox"),
    ("ppp", "ppp"),
    ("ppv", "ppv"),
    ("kev", "kev"),
    ("kdp", "kdp"),
    ("sep", "sep"),
    ("smp", "smp"),
    ("spi", "spi"),
    ("sshp", "sshp"),
    ("tpp", "tpp"),
    ("ttmi", "ttmi"),
    ("ttmp", "ttmp"),
    ("txtp", "txtp"),
    ("wdip", "wdip"),
    ("wheap", "wheap"),
    ("xhalp", "xhalp"),
    ("bip", "bip"),
    ("kz", "kz"),
    ("kx", "kx"),
    ("xm", "xm"),
    ("dxgkargcb", "dxgk::arg::cb"),
    ("dxgkarg", "dxgk::arg"),
    ("dxgiddicb", "dxgi::ddi::cb"),
    ("dxgkvgpu", "dxgk::vgpu"),
    ("verifier", "verifier"),
    ("security", "sec"),
    ("arbiter", "arbiter"),
    ("dxgkmdt", "dxgk::mdt"),
    ("d3dkmdt", "d3dk::mdt"),
    ("d3dddi", "d3d::ddi"),
    ("apphelp", "apphelp"),
    ("x86_bios", "x86bios"),
    ("devpkey", "devpkey"),
    ("dxgkcb", "dxgk::cb"),
    ("dxgkddi", "dxgk::ddi"),
    ("d3dkmt", "d3dk::mt"),
    ("dxgkdt", "dxgk::dt"),
    ("dbgkd", "dbgkd"),
    ("dxgi", "dxgi"),
    ("pshed", "pshed"),
    ("power", "power"),
    ("trace", "trace"),
    ("image", "image"),
    ("dbgkm", "dbgkm"),
    ("authz", "authz"),
    ("alpc", "alpc"),
    ("bapd", "bapd"),
    ("boot", "boot"),
    ("clip", "clip"),
    ("acpi", "acpi"),
    ("x_hal", "xhal"),
    ("clfs", "clfs"),
    ("dxgk", "dxgk"),
    ("kldr", "ldr::km"),
    ("ndis", "ndis"),
    ("whea", "whea"),
    ("pnpr", "pnpr"),
    ("x_kd", "xkd"),
    ("heap", "heap"),
    ("smss", "smss"),
    ("dxva", "dxva"),
    ("wwan", "wwan"),
    ("emon", "emon"),
    ("aux", "kaux"),
    ("cls", "cls"),
    ("csr", "csr"),
    ("dbgk", "dbgk"),
    ("perf", "perf"),
    ("dmar", "dmar"),
    ("hdls", "hdls"),
    ("dbg", "dbg"),
    ("dma", "dma"),
    ("efi", "efi"),
    ("xdv", "xdv"),
    ("dmm", "dmm"),
    ("etw", "etw"),
    ("hal", "hal"),
    ("ldr", "ldr"),
    ("vid", "vid"),
    ("video", "video"),
    ("pci", "pci"),
    ("drv", "drv"),
    ("ext", "ext"),
    ("gxp", "gxp"),
    ("kse", "kse"),
    ("lpc", "lpc"),
    ("pep", "pep"),
    ("pnp", "pnp"),
    ("pop", "pop"),
    ("hvl", "hvl"),
    ("xxx", "kuser::lt"),
    ("yyy", "kuser::ld"),
    ("zzz", "kuser::zz"),
    ("ppm", "ppm"),
    ("rpc", "rpc"),
    ("rtl", "rtl"),
    ("tpm", "tpm"),
    ("tag", "tag"),
    ("bgp", "bgp"),
    ("bcp", "bcp"),
    ("nls", "nls"),
    ("hid", "hid"),
    ("tlg", "tlg"),
    ("dwm", "dwm"),
    ("bcd", "bcd"),
    ("dmr", "dmr"),
    ("vi", "ver"),
    ("wsk", "wsk"),
    ("wil", "wil"),
    ("wmi", "wmi"),
    ("vhd", "vhd"),
    ("ngl", "ngl"),
    ("lsa", "lsa"),
    ("arb", "arb"),
    ("txt", "txt"),
    ("sdb", "sdb"),
    ("smc", "smc"),
    ("wdf", "wdf"),
    ("wdi", "wdi"),
    ("sec", "sec"),
    ("bgk", "bgk"),
    ("ttm", "ttm"),
    ("asi", "asi"),
    ("ahc", "ahc"),
    ("ssh", "ssh"),
    ("hsa", "hsa"),
    ("asl", "asl"),
    ("wnf", "wnf"),
    ("vrp", "vrp"),
    ("vf", "verf"),
    ("cc", "cc"),
    ("ci", "ci"),
    ("cm", "cm"),
    ("ex", "ex"),
    ("kz", "kz"),
    ("kx", "kx"),
    ("ki", "ki"),
    ("kd", "kd"),
    ("ke", "ke"),
    ("fs", "fs"),
    ("fx", "fx"),
    ("hv", "hv"),
    ("io", "io"),
    ("mi", "mi"),
    ("mm", "mm"),
    ("ob", "ob"),
    ("pm", "pm"),
    ("po", "po"),
    ("ps", "ps"),
    ("sm", "sm"),
    ("sp", "sp"),
    ("mx", "mx"),
    ("se", "se"),
    ("tp", "tp"),
    ("sk", "sk"),
    ("bi", "bi"),
    ("pi", "pi"),
    ("em", "em"),
    ("pf", "pf"),
    ("pp", "pp"),
    ("si", "si"),
    ("tm", "tm"),
    ("xm", "xm"),
    ("bg", "bg"),
    ("ae", "ae"),
    ("nt", "os"),
    ("zw", "os::km"),
];
